export const BOT_FLOWS = {
  // BOT FLOWS
  MENUOPTIONS: "MENU OPTIONS",
  FOODMENU: "FOODMENU",

  // GPT FLOWS
  GPT_ORDER: "GPT_ORDER",

  GPT_INIT_CONVERSATION: "GPT_INIT_CONVERSATION",
  GPT_ASK_NAME: "GPT_ASK_NAME",
  GPT_TAKE_ORDER: "GPT_TAKE_ORDER",
  GPT_ASK_LOCATION: "GPT_ASK_LOCATION",
  GPT_ASK_OBSERVATIONS: "GPT_ASK_OBSERVATIONS",
  GPT_SEND_PRE_BILL: "GPT_SEND_PRE_BILL",
  GPT_ASK_PAYMENT_METHOD: "GPT_ASK_PAYMENT_METHOD",
  GPT_SEND_COMPLETE_BILL: "GPT_SEND_COMPLETE_BILL",

  // OTROS
  // Si itera varios mensajes
  ITERATIVE: "ITERATIVE",
  // Default
  DEFAULT: "DEFAULT",
};
