export const BOT_FLOWS = {
  // BOT FLOWS
  MENUOPTIONS: "MENU OPTIONS",
  FOODMENU: "FOODMENU",

  // GPT FLOWS
  GPT_INIT_CONVERSATION: "GPT_INIT_CONVERSATION",
  GPT_TAKE_ORDER: "GPT_TAKE_ORDER",


  // OTROS
  // Si itera varios mensajes
  ITERATIVE: "ITERATIVE",
  // Default
  DEFAULT: "DEFAULT",
};
